apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-eu
  namespace: default
spec:
  instances: 3 # 1 primary + 2 replicas for high availability
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  # Configure primary instance
  primaryUpdateStrategy: unsupervised

  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"

  bootstrap:
    initdb:
      database: app
      owner: app

  # Storage configuration
  storage:
    size: 1Gi
    storageClass: standard

  monitoring:
    enablePodMonitor: false
    tls:
      enabled: false

  # Resources
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  # Specify where pods should be scheduled
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  env:
    - name: TZ
      value: "UTC"
