apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pg-eu
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: cnpg-monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      cnpg.io/cluster: pg-eu
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
